{% set name = "yaqd-scpi" %}
{% set version = "2021.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqd-scpi-{{ version }}.tar.gz
  sha256: ddad2e05e4eb2a91525fc00f671936096030a8863125ee772a35b1cf7f82baed

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-scpi-sensor = yaqd_scpi._scpi_sensor:SCPISensor.main
    - yaqd-scpi-set-continuous = yaqd_scpi._scpi_set_continuous:SCPISetContinuous.main
    - yaqd-scpi-set-discrete = yaqd_scpi._scpi_set_discrete:SCPISetDiscrete.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - flit
  run:
    - python >=3.7
    - pyvisa
    - pyvisa-py
    - yaqd-core >=2020.10.0
    - flit

test:
  imports:
    - yaqd_scpi
  commands:
    - pip check
    - yaqd-scpi-sensor --help
    - yaqd-scpi-set-continuous --help
    - yaqd-scpi-set-discrete --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for SCPI hardware
  dev_url: https://gitlab.com/yaq/yaqd-scpi
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BrandonMehlenbacher
    - untzag
    - ksunden
